<?php

namespace FA\Tests\Authentication\Adapter;

use FA\Authentication\Adapter\DbAdapter;
use Zend\Authentication\Result;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-13 at 07:43:23.
 */
class DbAdapterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DbAdapter
     */
    protected $adapter;
    
    /**
     * @var \Phpass\Hash
     */
    protected $hasher;

    /**
     * @var FA\Dao\UserDao
     */
    protected $dao;
    
    /**
     * @var array
     */
    protected $user;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->dao = $this->getMock('FA\Dao\UserDao', array('findByEmail', 'recordLogin'), array(), '', false);
        $this->hasher = $this->getMock('\Phpass\Hash');
        $this->adapter = new DbAdapter($this->dao, $this->hasher);
        
        $this->user = array(
            'id' => '1',
            'email' => 'user@example.com',
            'password_hash' => '$2y$12$pZg9j8DBSIP2R/vfDzTQOeIt5n57r5VigCUl/HH.FrBOadi3YhdPS',
            'last_login' => null
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->adapter = null;
        parent::tearDown();
    }

    public function testCreation()
    {
        $this->assertInstanceOf('FA\Authentication\Adapter\DbAdapter', $this->adapter);
    }

    /**
     * @covers FA\Authentication\Adapter\DbAdapter::authenticate
     */
    public function testAuthenticateSuccess()
    {
        $this->dao->expects($this->once())
                ->method('findByEmail')
                ->with($this->user['email'])
                ->will($this->returnValue($this->user));

        $this->hasher->expects($this->once())
                ->method('checkPassword')
                ->with('password', $this->user['password_hash'])
                ->will($this->returnValue(true));
        
        $this->adapter->setCredentials('user@example.com', 'password');
        $result = $this->adapter->authenticate();
        
        unset($this->user['password_hash']);

        $this->assertInstanceOf('\Zend\Authentication\Result', $result);
        $this->assertEquals($this->user, $result->getIdentity());
        $this->assertEquals(Result::SUCCESS, $result->getCode());
        $this->assertEquals(array(), $result->getMessages());
    }

    /**
     * @covers FA\Authentication\Adapter\DbAdapter::authenticate
     */
    public function testAuthenticateFAilure()
    {
        $this->dao->expects($this->once())
                ->method('findByEmail')
                ->with($this->user['email'])
                ->will($this->returnValue($this->user));
        
        $this->hasher->expects($this->once())
                ->method('checkPassword')
                ->with('badpassword', $this->user['password_hash'])
                ->will($this->returnValue(false));

        $this->adapter->setCredentials('user@example.com', 'badpassword');
        $result = $this->adapter->authenticate();

        $this->assertInstanceOf('\Zend\Authentication\Result', $result);
        $this->assertEquals(array(), $result->getIdentity());
        $this->assertEquals(Result::FAILURE_CREDENTIAL_INVALID, $result->getCode());
        $this->assertEquals(array('Invalid username or password provided'), $result->getMessages());
    }
    
    public function testAuthenticationUserNotFound()
    {
        $this->dao->expects($this->once())
                ->method('findByEmail')
                ->with('user@example.org')
                ->will($this->returnValue(false));
        
        $this->adapter->setCredentials('user@example.org', 'userdoesnotexist');
        $result = $this->adapter->authenticate();
        
        $this->assertInstanceOf('\Zend\Authentication\Result', $result);
        $this->assertEquals(array(), $result->getIdentity());
        $this->assertEquals(Result::FAILURE_IDENTITY_NOT_FOUND, $result->getCode());
        $this->assertEquals(array('Invalid username or password provided'), $result->getMessages());
    }

}
