<?php

namespace FA\Tests\Service;

use FA\Service\ImageService;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-15 at 21:30:13.
 */
class ImageServiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ImageService
     */
    protected $service;

    /**
     * @var \FA\Dao\ImageDao
     */
    protected $dao;

    /**
     * @var \FA\Service\FlickrService
     */
    protected $flickr;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->dao = $this->getMock('FA\Dao\ImageDao', array('find', 'findAll', 'save', 'delete'), array(), '', false);
        $this->flickr = $this->getMock('FA\Service\FlickrService', array('getSizes'), array(), '', false);
        $this->service = new ImageService($this->dao, $this->flickr);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->service = null;
    }

    /**
     * @covers FA\Service\ImageService::find
     */
    public function testFind()
    {
        $imageData = array('day' => '1', 'photo_id' => '7606616668');
        $imageSizes = array('sizes' => array('size' => array()));

        $this->dao->expects($this->once())
                ->method('find')
                ->with($imageData['day'])
                ->will($this->returnValue($imageData));

        $this->flickr->expects($this->once())
                ->method('getSizes')
                ->with($imageData['photo_id'])
                ->will($this->returnValue($imageSizes));

        $result = $this->service->find($imageData['day']);

        $this->assertEquals(array_merge($imageData, $imageSizes), $result);
    }

    public function testFindImageDoesNotExist()
    {
        $this->dao->expects($this->once())
                ->method('find')
                ->with('222')
                ->will($this->returnValue(false));

        $this->flickr->expects($this->never())->method('getSizes');

        $this->assertNull($this->service->find('222'));
    }

    /**
     * @covers FA\Service\ImageService::findAll
     */
    public function testFindAll()
    {
        $imageData = array(
            array('day' => '1', 'photo_id' => '11'),
            array('day' => '2', 'photo_id' => '22'),
            array('day' => '3', 'photo_id' => '33')
        );

        $imageSizes = array(
            array('sizes' => array(11)),
            array('sizes' => array(22)),
            array('sizes' => array(33))
        );

        $this->dao->expects($this->once())
                ->method('findAll')
                ->will($this->returnValue($imageData));

        $expected = array();
        
        // The Flickr service should be called as many times as there are
        // data elements returned from the dao
        foreach ($imageData as $index => $image) {
            
            $expected[] = array_merge($image, $imageSizes[$index]);
            
            $this->flickr->expects($this->at($index))
                    ->method('getSizes')
                    ->with($image['photo_id'])
                    ->will($this->returnValue($imageSizes[$index]));
        }
        
        $result = $this->service->findAll();
        
        $this->assertEquals($expected, $result);
    }

    /**
     * @covers FA\Service\ImageService::save
     */
    public function testSave()
    {
        $this->dao->expects($this->once())
                ->method('save')
                ->with(array('day' => 200, 'photo_id' => 999999))
                ->will($this->returnValue(1));
        
        $this->assertEquals(1, $this->service->save(array('day' => 200, 'photo_id' => 999999)));
    }

    /**
     * @covers FA\Service\ImageService::delete
     */
    public function testDelete()
    {
        $this->dao->expects($this->once())
                ->method('delete')
                ->with(200)
                ->will($this->returnValue(1));
        
        $this->assertEquals(1, $this->service->delete(200));
    }

}
